### ISSUE TITLE
Cannot close when used in a container that can be scrolled . 

### ISSUE THREAD

**Issue by guangzan** [francoischalifour/medium-zoom#160]
## Bug description

> The scroll bar is not in the body. I use it in a container that can be scrolled. Medium zoom acts on the image of this container. When the image is opened, it cannot be closed by scrolling, and the container cannot be scrolled.

## Expected behavior

> It can be closed when scrolling .

**Comment by francoischalifour** [comment]
Can you please replicate the behavior in this [sandbox](https://codesandbox.io/s/github/francoischalifour/medium-zoom/tree/master/examples/vanilla)?

**Comment by guangzan** [comment]
Like this [sandbox](https://codesandbox.io/s/cranky-taussig-oux9g?file=/src/style.css) . Thanks.

**Comment by francoischalifour** [comment]
This is expected because we append the zoomed image to the `body`, which doesn't have any scroll padding in that case.

As a workaround, you can increase the `body` `height` when an image is zoomed (`.medium-zoom--opened`). I created an example [in this sandbox](https://codesandbox.io/s/winter-silence-0n2s0?file=/src/style.css:452-573).

**Comment by guangzan** [comment]
Thank you so much .
