### ISSUE TITLE
Is medium-zoom conflict with html style zoom?

### ISSUE THREAD

**Issue by qrzbing** [francoischalifour/medium-zoom#164]
## Bug description

When I want to use `<img src="xxx" style="zoom: 80%;" class="medium-zoom-image">` will cause image in wrong location.

![bug](https://user-images.githubusercontent.com/23500397/103984075-6762d380-51c1-11eb-8cf2-fb6ba76b8eb9.gif)

## How to reproduce

See website on <https://nuaa-s3lab.github.io/dailyPaper/2021/0104.html>, the second image and images after have this error. HTML language of image is: 

``` html
<img src="/dailyPaper/assets/img/3.e02d285c.png" style="zoom: 67%;" class="medium-zoom-image">
```

## Expected behavior

See image in the center of paper

## Reproducible example

[Link to the bug reproduction](https://nuaa-s3lab.github.io/dailyPaper/2021/0104.html)

## Environment

 - Browser: Chrome / 87.0.4280.88
 - `medium-zoom` version: 1.0.4

**Comment by francoischalifour** [comment]
Medium Zoom doesn't reset the `style` of the zoomed image because some user styling might still be expected on the zoomed image. However, you should remove the `zoom` style property from the zoomed image because it conflicts with the computed zoom styles.

This logic can be executed in a [Medium Zoom event](https://github.com/francoischalifour/medium-zoom#events), manipulating the zoomed images `style`:

```ts
// In the event
document.querySelectorAll('.medium-zoom-image--opened').forEach(x => x.style.zoom = '');
```
