### ISSUE TITLE
SVG images shrink instead of expand

### ISSUE THREAD

**Issue by garviand** [francoischalifour/medium-zoom#52]
Love the plugin, thanks for all of your work.

I have a mix of SVGs and PNGs on my site, and the PNGs are expanding beautifully, but when the SVG images are clicked they actually get smaller.

Let me know if you have run into this before.

**Comment by francoischalifour** [comment]
Hi, are you talking about an `img` element having a SVG as a source (`src`)? (as opposed to an actual [`svg`](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/svg) element)

The library hasn't been thought with this in mind. I'm not sure how different the `img` element behaves with a PNG and a SVG.

I will investigate in the next days or if you want to get involved, feel free to do so 🙂

**Comment by francoischalifour** [comment]
I reproduced this issue [in a sandbox](https://codesandbox.io/s/82llzv0980).

The reason of this behavior is because a SVG doesn't handle its `naturalWidth` and `naturalHeight` the same way as a PNG or a JPG.

Since a SVG cannot pixelize, a solution could be to consider that its full size is the screen size. You could then adjust the zoom with margins.

What do you think @garviand?

**Comment by btlewan** [comment]
The natural width of SVG images varies across browsers, because they don't use the viewbox settings for sizing purposes. Even with commit 104f18b, zoomed SVGs appear smaller in Chrome than unzoomed images (unless they're smaller than 300x150).

I think it would be better to use the viewport width/height for SVGs in all cases. I'll see about creating a PR to that effect.

**Comment by francoischalifour** [comment]
The referenced commit should solve this issue since it's based on the viewport. You can check the behavior on [this story](https://medium-zoom.francoischalifour.com/storybook/?selectedKind=SVG&selectedStory=default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fnotes%2Fpanel).

Note that I haven't released it yet.

**Comment by btlewan** [comment]
I've just tried the released version, and it works! Thanks very much for the update.
