### ISSUE TITLE
Add lazy-load support

### ISSUE THREAD

**Issue by cwang22** [francoischalifour/medium-zoom#59]
Hi, great work and loved it 👍 

would you consider add lazy-load support?

e.g. provide an option to bind the event listener on the selector instead of the <img> itself, so it works for lazy-loaded images?

Thanks.

**Comment by francoischalifour** [comment]
Hi there, I don't think this is the responsibility of this library.

If you use another library to lazy load your images, you can dynamically apply the zoom to the images once they're loaded.

Does that make sense?

**Comment by cwang22** [comment]
yeah, didn't think this way, thanks

**Comment by knynkwl** [comment]
I feel like some type of image loaded event would be nice.

If the image is large then it would be nice to set a loading class and only open the modal when the image has loaded. I am running into problem where the image is large and the modal shows with the thumbnail not expanded, then a second or two later the image will expand.

**Comment by francoischalifour** [comment]
To avoid the loading time, you can preload the large images when the thumbnails enter in the viewport. You can use the [Intersection Observer API](https://developer.mozilla.org/docs/Web/API/Intersection_Observer_API) for this. I don't think this should be part of Medium Zoom because it becomes too opinionated. Besides, it is not very hard to implement on user-land.

I made an example [on this sandbox](https://codesandbox.io/s/1y2xmzmwll). You can see that the large version of the images load when the thumbnails enter in the viewport.

Check the network requests on this GIF:

![mz-intersection-load](https://user-images.githubusercontent.com/6137112/54883481-54550700-4e66-11e9-9c97-565ae2611d99.gif)

Let me know if that can solve your problem. Otherwise, we can work together to define a better API.

_Note: I will work on a plugin system for Medium Zoom including a router, a preload system, and a slide system. These will be plugins for Medium Zoom, and not part of the core. There's no ETA yet._

**Comment by knynkwl** [comment]
This can work. A plugin system would be awesome though!
